### ISSUE TITLE
Always show farm rate on battle screen

### ISSUE THREAD

**Issue by corfe83** [corfe83/IdleArmadaIssues#139]
Per minute, per hour, per day

**Comment by ghost** [comment]
This may be an excellent position for it:
![image](https://user-images.githubusercontent.com/40145743/94550204-9788f680-0210-11eb-9e6e-8832d39ac468.png)
Maintaining the current size would be intrusive.

**Comment by corfe83** [comment]
Fixed in next release. It did fit there.
