### ISSUE TITLE
Enhanced Factory System

### ISSUE THREAD

**Issue by ghost** [corfe83/IdleArmadaIssues#142]
Each completed level would offer a special currency which I will refer to as 'Ship Tokens' for the duration of this passage. 
Tokens may be expended upon new factories, incrementing a new ship to your arsenal. However, the token price of each vessel would correspond to your job and therefore, while not demanding a battallion of cargo bays as merchant, would encourage the player to select relevant types for the run duration. Tokens would likely be provided per level - potentially incrementing at some battle intervals - and each new factory would ineluctably feature its regular cost in resources. If during any event a factory is discarded, a quantity (_not_ all) of the allocated resources are returned - potentially rising by prestige benefit - unless exceeding storage capacity. However, worry not for level one hundred. To mitigate an infinite fleet, the token expense of all ships would escalate each individual purchase. In regards to selection for amateur players, job ships (miner, assassin, etc) too should be restricted until prestige in corresponding classes. This would replace the current system of factory unlocks that occur in the initial ten levels and append a new level of complexity and variety to fleet creation. Obviously, this aligns to my anticipations of precisely-customized fleet formations and gameplay immersion.

**Comment by corfe83** [comment]
Suggestion from cwestbrook20 on discord: Maybe when you make out the custom factory/fleet setup, a player can select what ship they want to be their "Flagship" and that would grant it some type of X,Y,Z bonus (or a job that only gives Flagship bonuses)

**Comment by corfe83** [comment]
This is fixed, the other suggestion is now described by #304
