### ISSUE TITLE
Some indication the game isn't stuck when simulating long battles

### ISSUE THREAD

**Issue by darkscott** [corfe83/IdleArmadaIssues#145]
Either an animation, or idle items picked up, or something...

When simulating battles at the end game, the battles are veeerrrrryyyyyyy long.  The screen offers no visual indication that it isn't stuck.  

You also don't know how much is left to simulate, which can also be several minutes at high levels.

**Comment by corfe83** [comment]
Fixed in upcoming release. There are probably improvements I can do in speed here, but at least now you'll be able to see the progress in real time to understand what it's doing.
