### ISSUE TITLE
FPS skyrockets in fullscreen mode

### ISSUE THREAD

**Issue by corfe83** [corfe83/IdleArmadaIssues#147]

**Comment by scm-xbox** [comment]
The engine should force v-sync for the render pipeline, which will prevent the fullscreen rendering from exceeding the capabilities of the monitor.

**Comment by darkscott** [comment]
The engine should force vsync on in the rendering settings.  This will prevent the rendering from going faster than the capabilities of the monitor, which will usually be between 60 and 144fps for most monitors.

**Comment by corfe83** [comment]
Fixed in next release
