### ISSUE TITLE
Victory counter doesn't increment when fast-forwarding battles

### ISSUE THREAD

**Issue by darkscott** [corfe83/IdleArmadaIssues#163]
I have not confirmed this is always the case, but I fast forwarded 2 levels (that took a long time to win... close to 300 seconds), and Victory never incremented even though I completed levels 81 and 82 while in Fast-Forward mode.

Expected that these should count as victories, unless I'm misunderstanding what Victory means...

**Comment by corfe83** [comment]
Thanks for reporting, I agree this is a bug and I think I might know the cause.

**Comment by corfe83** [comment]
On second thought, this isn't expected behavior, but I wasn't able to reproduce it. My theory I commented about earlier turned out to be incorrect.

I don't think I've made any changes since this was filed that would have fixed it, so I'm going to leave this open for now.

**Comment by corfe83** [comment]
I'm cleaning up old bugs -- a lot of changes have happened since this was filed, and I am unable to reproduce this in the recent version. I suspect it's been fixed, please reactivate if you believe it's still happening.
