### ISSUE TITLE
Cannot change levels while calculating items per second

### ISSUE THREAD

**Issue by darkscott** [corfe83/IdleArmadaIssues#164]
This is only really an issue in end-game.  Levels take a LONG TIME to simulate (sometimes 30+ seconds).  If you want to go back 3 levels, it can take a long time to do so waiting for each to calculate.

The UI should be responsive to changing levels, even if it doesn't complete the calculation (the calculation can be canceled and the new level's calculation can start)

**Comment by corfe83** [comment]
Thanks for reporting, yeah as you suspected this is a guard to make sure we don't have multiple calculations going on at once, and what I really need is a mechanism to cancel the background calculation so we can fire a new one.

Will fix.

**Comment by corfe83** [comment]
Fixed in next release
