### ISSUE TITLE
Rewards for beating levels scale too slowly

### ISSUE THREAD

**Issue by darkscott** [corfe83/IdleArmadaIssues#25]
The amount of resources you get for beating a level do not match the difficulty / investment needed to clear the level.  

Beating a level should provide enough of a resource boost to feel significant, without being too much (too much is defined as: enough resources that you can buy yourself through the next level off of just the reward).

**Comment by corfe83** [comment]
I forgot to close this, but this was increased in earlier release. If anyone feels it's not enough now, feel free to let me know on discord.
