### ISSUE TITLE
Boss ship levels rewards should be higher than normal levels

### ISSUE THREAD

**Issue by darkscott** [corfe83/IdleArmadaIssues#26]
Sort of a duplicate of the generic levels rewards, but this is specifically for boss levels.  Boss rewards should be significantly higher than a normal level.  Rewards for boss levels should also be considered for Prestige buffs that augment their amounts.  This includes job points being more than normal levels.

**Comment by corfe83** [comment]
In next update, boss ship level rewards are now much higher (4x) than normal level rewards, and level rewards are generally higher in the game overall.

I'll keep the idea about prestige ability that increases rewards in mind, I have to think about it.
