### ISSUE TITLE
Tabs with maxed resources should be colored differently

### ISSUE THREAD

**Issue by darkscott** [corfe83/IdleArmadaIssues#27]
When a resource in a given tab has a maxed resource, the tab for that resource should be colored differently in all the other screens to let you know that you should look at it.  (Example: Maxed insight points should make the Insights tab change colors.)

**Comment by corfe83** [comment]
Yep, agreed, this needs to be improved.

**Comment by corfe83** [comment]
Also, when a purchase is available, tab should also show something visual.

**Comment by corfe83** [comment]
This is fixed
