### ISSUE TITLE
Bullets that miss their original target should retarget a ship close to the bullet

### ISSUE THREAD

**Issue by darkscott** [corfe83/IdleArmadaIssues#28]
When bullets are going to a target that's been destroyed, they go to the next highest value target.  The problem with this is high value targets are often far away from each other due to the semi-random layout of the ships.  This means that missed shots will often pinball around the screen not hitting anything as by the time they reach their next target, it's already been destroyed by new shots fired from the ships.

Missed shots should probably prioritize hitting something as soon as possible, over hitting the highest value target.

**Comment by corfe83** [comment]
Yeah, that is annoying. Thanks for filing it, will fix.

**Comment by corfe83** [comment]
Will be fixed in next release.
