### ISSUE TITLE
Add ship type button is confusing in that it requires land

### ISSUE THREAD

**Issue by corfe83** [corfe83/IdleArmadaIssues#308]
Why not allow folks to add a ship type and see the +/- buttons whenever they want?

**Comment by ghost** [comment]
That more land is necessary should be obvious. Rather, if ships were _not_ to initiate at level one, why even purchase them? You must waste another click only to learn you cannot yet attain the desired vessel anyways.

Better idea: the 'add ship' button becomes yellow if unable to purchase a ship; you cannot append any but _can_ view for reference.

**Comment by corfe83** [comment]
This is now slightly better in that the add ship type button shows the cost of the next ship you can add, but I'm leaving this open as it would be even better if you could open the UI and see the cost of the ship you want

**Comment by corfe83** [comment]
Now you can open this UI anytime to at least see the ships you might add
