### ISSUE TITLE
Possible problem with auto item pickup

### ISSUE THREAD

**Issue by corfe83** [corfe83/IdleArmadaIssues#316]
Some people are reporting. Need to confirm or refute.

**Comment by bottekott** [comment]
I have this issue. Here is a save game if you need it :)

mbx:H4sIAAAAAAAC/5yZS4/bqhfAv4vXVmTwC2fX6X/zv2qr3k7Vu6i6IA7j0NgQAZ7eUTXf/QpsJ+bhxh510RHw83lwOOdAfkffiJCUs2j/O/pCWoIlifZJHH3EP7mI9lUcfaRM/wWSOPqMVX2K9vA1jh7xM3kgDWVfaUeiPcirsspgjvKsKOLoA5bqsyBS0YaMC4oEwTLLsjwtcv3RtqWS1Jwd5TiJYAJKhNI4+kIk70VNpFbqf1hh/X8tXqTCrf7zXcd7pqI9rFIECwTRrijLpEqKLI6+UUkPLYn2SvTkNZ6wmneXOQpyhJIdqGCSpyBDJUx99Inzo8WUMIMpKHdFmuawytMizLiyEERVsqtAkWUQlBkofazhrSUqLRKQJDnYgaJEEGiPuQhlkjYnZfkD7UCRFWkCyzxJkiRg009+uFgMKAKrWswcy/Mky3Y5KLMc6c0KmNARd3dAnoG8ALsiL/ICJQgtQK6/CljCHcrLChQQJCkCPidrSlhNLGpQscrTDMGyqlzo9TWO/uIHK6aO5An3rfGHtTiOpuB9PzoAmagkSg7RfyRPhElyH4SZDRLWUEaIuE86Ep+w6O5DuQ1NYXVHx8SmOsqGo3fHJ8DGBGbNCo8AaGPy8rJVlt7Kh562R8oaaz9xV4snXJsN/UCeSRvt0/I1NuMdEfV8PHmNowPvDsQlMnidcRgIzAyXSp4oGVw7TqFM5xosGu5+Lb0lIWcKJrcp7fO5dug2JRUX8zmQz8JhHMuzMfc4IkA5jnsf0aY0PRYukVbThOuwgWjbkLv0uOuswiQpxudSU5NcDu4+mDQQUt1MOL7JroRnVDpGr7elyS1neJCeU0QIPNdqCLL/DznWjjHRcTFfquNLKVyf5YWQeUyk2gNH3OFmLi+/pYHZqF7qBZX2uFSCs8abSiuj4OMtD076TWd++gaya8V8/zvKKGvc0NIOslUGYPCGIp38h6rTRyzOlk8OtJEnfvu+jPbfk1j/Az/85H1ocX1Wp7loGe1Z37ahtT1Zu1TwX2zl2mOPW0/jMg8o+0QFkSdrHUhLbVmcxDAANIKQtWqcGa/Pntf0l0OqdL31ye9VElgkyHGlcEEawk592zrG/VhY6nihCKwbwhRLSaXtWgDgYjgM0IUSUZP7Wutd4+xIsLLVyfIf4cWCXIhtYpEsLu0luR8S8kLPRAl8WaGt6tkK2apn7ve+w1BwKUHdsA0J1qf1U9+ZA6szXIni6PFEL16xnDdQOt8euoM7VIvGamZNiB+9ob51hzrmfN4kLKLUVLU/8Xe94qasP2ClZmb+3dP6/NCbxuCg0xkEWZmhtMhKk8zsgY629oCs6XxAdwvm+1M10Jca/K81lpdx9LVXXFDcPipyke95d2mJ0gkdwls/YjmwbfmLrjTcFGox9NW1os/TVzVImG5TpgFdLDRGWc074gOZR2Rj/3LAktyKiUVVLlSNzJHKevC+Q4DURUzt1MyJ4HY4Wzbh2QLg1FlhcRbk2Ne+ZubSaFPJSN1Kmk3kHqGLEpZYLli/JEMTi/YvM1NGXLN+6BL1zixYg1wMGYr18totW+tT4AIpsIie+crB0guacupGt/nMIPJEL1sddwXlaTVCRd1TtXQQvJiGlX2bXzhxXvjA/NqFLVpVuJDp3ASmTO/tlogw0FbvGYj86YQvgKTmjHcvP/nBjyQvkK5tp/S95sUpRLPHjE2u1tDSpnpKwXR2PwkZHtwZ3eIuiEi9BJpmFhE6QKnnXXMr0dCC6R4ALQCuSwTmmrV91w22Ncb0De1PosIFwabgakeMWPDkBKuVJt5i0vbao3Uy+XRtHr0CcO25uRLpWoed3mC+vls/10yJ7aC5DS6dIO9Yp/pYU0W66dYUPhRL0hTphkvUprOksa5vNouaX0HeAI/3hQXSCxDzSHEje0neJFPObjSrOdWz7cLGm8YmsCOiXo6xcF94fdjdVDtsanW66WhLFRbBOhhswbs75TaYra/Qln5geGLZVqzmDFzt8Bm0ocbp83LRSbSm6+NhYqZHSAvydjafI6Z2+YK8tnd4n5ooHYGndYXEdMmL0RpUTmBFOdt+kRu4pV4nXBrGR8jVkTqks4V6FT5EMyQQPV7Igcxm/JoFPFPMo+KM2RBwA7W1ZA1U12zm9G46T+wW52X0MkDBdXE0x5b6WT/QwyBc19Ab8vo75brl4SPoxUV2Wx9Id8sOmP8uuU6A9ci/cneuzBZHXX802LYzcwxusOsXVafbQ/9KHTW08ARzB+rb1rzTrrtDXbmld5hFd9ygjqqN7hi4sJoL5i3sVvi+MvxaEizQgZo+PpNOb3vmqbQyvxLrSPsvAAD//ypexeUbIQAA:xbm

**Comment by corfe83** [comment]
I believe this has been fixed now.
