### ISSUE TITLE
On Moto G6, sometimes returning to app results in black screen until app is restarted

### ISSUE THREAD

**Issue by corfe83** [corfe83/IdleArmadaIssues#41]

**Comment by corfe83** [comment]
I updated to a new version of ebiten which had fixes for these bugs, one of which might be related:

https://github.com/hajimehoshi/ebiten/issues/1314
https://github.com/hajimehoshi/ebiten/issues/1322

**Comment by hajimehoshi** [comment]
Or, hajimehoshi/ebiten#1332 might be related :)

**Comment by corfe83** [comment]
I messaged the user who had this problem a few days ago and haven't gotten a response. Closing this to cleanup the list, but will reactivate if I hear back that it didn't work.

**Comment by RicardoGzz** [comment]
This sounds like an opengl context lost, you might be able to reproduce this on any android phone if you call setPreserveEGLContextOnPause(false) on your GLSurfaceView

**Comment by corfe83** [comment]
Thanks @RicardoGzz , good call -- if it pops up again I will keep this in mind!
