### ISSUE TITLE
Reduced idle collection of items

### ISSUE THREAD

**Issue by Tobynator** [corfe83/IdleArmadaIssues#63]
With item marks allowing for significant increases in active collection, the game is less reliant on passive item collection. There are three possible ways to do this, and more than one can be used:
Cap item drops per minute (the value 20 was suggested)
Nerf idle collection rate
Make idle collection trigger at item disappearance, and does not get a bonus for picking up higher mark items.

**Comment by corfe83** [comment]
I think this has been mitigated since the item marks update, due to items having lower caps. I really like this suggestion though, so leaving it open to track fixing that:

**Make idle collection trigger at item disappearance**

**Comment by corfe83** [comment]
Fixed in upcoming release that auto item collection only triggers when items are about to fade out (instead of when they first appear)
