### ISSUE TITLE
Item battle level scaling

### ISSUE THREAD

**Issue by Tobynator** [corfe83/IdleArmadaIssues#64]
Items effects should not be multiplied by battle level, but instead battle level should put a soft cap on how effective they are. That means that they get diminishing returns beyond some item level that increases with battle level. This should be an exponential increase, for example 10% per level compounding. 10% is probably a bit high, but the exact factor can be adjusted easily after testing.

**Comment by corfe83** [comment]
I believe item mark levels is the solution to this.

Edit: I mean I believe the way item mark levels was implemented also solves this. You get diminishing returns if your items are undermarked for your level, so if progress is slow, you are encouraged to farm high levels to get those high mark itemd and go forward again
